name: Build wheels

on:
 [push]

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-22.04, macos-13, windows-latest]
        python-version: ["3.11", "3.12", "3.13"]
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Set up Python ${{ matrix.os }} ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          architecture: 'x64'
      - name: Install dependencies
        run: python -m pip install --upgrade pip build pillow numpy
      - name: Build
        run: ${{ (startsWith(matrix.os, 'macos') && 'MACOSX_DEPLOYMENT_TARGET=11') || '' }} python -m build --wheel
      - name: Test
        run: python -m unittest ./tests/test_from_python.py
      - name: Upload whl file
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}-${{ matrix.python-version }}-whl
          path: dist/*.whl
