name: Python package

on:
  push:
    tags:
      - 'v*'

jobs:
  build-native:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04, ubuntu-22.04-arm, macos-latest, windows-latest, windows-11-arm]
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: recursive
      - uses: pypa/cibuildwheel@v3.4.0
      - uses: actions/upload-artifact@v7
        with:
          name: wheels-${{ matrix.os }}
          path: wheelhouse/*.whl

  build-pyodide:
    name: Build Pyodide wheels
    strategy:
      matrix:
        python-version: ["3.12", "3.13", "3.14"]

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - uses: actions/setup-node@v4
        with:
          node-version: "24"

      - name: Install pyodide-build
        run: pip install pyodide-build

      - name: Build wheel
        run: pyodide build .

      - name: Test wheel
        run: |
          pyodide venv .venv-pyodide
          source .venv-pyodide/bin/activate
          pip install numpy pillow dist/*.whl
          python -m unittest ./tests/test_from_python.py

      - uses: actions/upload-artifact@v7
        with:
          name: wheels-pyodide-${{ matrix.python-version }}
          path: dist/*.whl

  publish-to-pypi:
    needs: [build-native, build-pyodide]

    environment:
      name: pypi
      url: https://pypi.org/p/cmm-16bit
    permissions:
      id-token: write

    runs-on: ubuntu-latest

    steps:
    - uses: actions/download-artifact@v5
      with:
        pattern: wheels-*
        path: dist
        merge-multiple: true

    - uses: pypa/gh-action-pypi-publish@release/v1
